networks:
  app-tier:
    driver: bridge
services:
  app:
    build: ./app
    command: tail -F /dev/null
    container_name: flask
    environment:
      MARVEL_API_HASH: 6a1ffed8298067ed61148c2c7db12935
      MARVEL_API_KEY: 2a346d86972cc65d7982367dae7758af
      MARVEL_API_TIMESTAMP: 1654341445
      SQL_DATABASE: intel
      SQL_HOST: db
      SQL_PASSWORD: root
      SQL_PORT: '3306'
      SQL_USER: root
    links:
    - db
    networks:
    - app-tier
    ports:
    - 5050:5050
  db:
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    hostname: db
    image: mysql:5.7
    networks:
    - app-tier
    platform: linux/x86_64
    ports:
    - 32000:3306
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
version: '3'
